package in.technitab.teamapp.util;

import java.util.ArrayList;

import in.technitab.teamapp.model.BookingMode;
import in.technitab.teamapp.model.State;


public class ConstantVariable {
    public final static String BASE_URL = "http://staging.teamapp.in/login/";
    public final static String BASE_TEXT_URL = "http://teamapp.in/login/";
    public static final String BASE_FIX_ASSET_URL = BASE_URL + "fix_asset/";
    public static final String BASE_TEC_URL = BASE_URL + "doc/tec/";
    public static final String CHANNEL_ID = "ESS";
    public static final String CHANNEL_NAME = "Employee Self Service";
    public static final String CHANNEL_DESCRIPTION = "www.technitab.in";
    public static final String REQUEST_LEAVE = "request_leave";
    public static final String LEAVE_APPROVED = "leave approved";
    public static final String LEAVE_REJECTED = "leave rejected";
    public static final String TEC_ = "tec";
    public static final String LEAVE_CANCEL = "cancel leave";
    public static final String LIST = "list";
    public static final String TRIP_BOOKINGS = "trip_bookings";
    public static final String BOOKING_JSON = "booking_json";
    public static final String PAYMENT_JSON = "payment_json";
    public static final String REQUEST = "request";
    public static String punchin = "You have Successfully Punched In";
    public static String punchout ="You have Successfully Punched Out";

    public static class UserPrefVar {
        public static final String USER_FILE = "user_file";
        public static final String USER_ID = "user_id";
        public static final String USER_ROLE = "user_role";
        public static final String NAME = "name";
        public static final String IMAGE = "image";
        public static final String EMAIL = "email";
        public static final String NUMBER = "mobile_number";
        public static final String IS_LOGIN = "is_login";
        public static final String ROLE_ID = "role_id";
        public static final String ACCESS_CONTROL_ID = "access_control_id";
        public static final String FCM_TOKEN = "fcm_token";
        public static final String RELATED_TABLE = "related_table";
        public static final String BASE_OFFICE_LOCATION = "base_office_location";
        public static final String Task_id = "Task_ID";
        public static final String LATITUDE = "latitude";
        public static final String LONGITUDE = "longitude";
        public static final String ADDRESS = "address";
        public static final String TYPE_ID = "TYPE_ID";
        public static final String ID = "id";
        public static final String NAMES = "names";
    }

    public static class Tbl_Task {
        public static final String ID = "id";
        public static final String NAME = "name";
        public static final String IS_DONE = "is_done";
        public static final String DATE = "created_date";
    }

    public static class Tbl_Attendance {
        public static final String ID = "id";
        public static final String DATE = "date";
        public static final String ATTENDANCE = "attendance";
        public static final String PUNCH_IN = "punch_in";
        public static final String PUNCH_OUT = "punch_out";
        public static final String MANUAL_PUNCH_IN = "manual_punch_in";
        public static final String MANUAL_PUNCH_OUT = "manual_punch_out";
        public static final String MANUAL_PUNCH_SYS_IN = "manual_punch_sys_in";
        public static final String MANUAL_PUNCH_SYS_OUT = "manual_punch_sys_out";
        public static final String SPENT_TIME = "spent_time";
        public static final String IN_PHOTO_PATH = "in_photo_path";
        public static final String OUT_PHOTO_PATH = "out_photo_path";
        public static final String IN_ADDRESS = "in_address";
        public static final String OUT_ADDRESS = "out_address";
        public static final String IN_LOCATION = "in_location";
        public static final String OUT_LOCATION = "out_location";
        public static final String SUMMERY = "summery";
        public static final String PUNCH_STATUS = "punch_status";
        public static final String MONTH_YEAR = "month_year";
        public static final String TIMESHEET_HOURS = "timesheet_hours";
        public static final String SYNC_STATUS = "sync_status";
    }


    public static class Tbl_LEAVE {
        public static final String ID = "id";
        public static final String REQUESTED_DATE = "requested_date";
        public static final String START_DATE = "start_date";
        public static final String END_DATE = "end_date";
        public static final String START_DATE_LEAVE_TYPE = "start_date_leave_type";
        public static final String END_DATE_LEAVE_TYPE = "end_date_leave_type";
        public static final String DESCRIPTION = "description";
        public static final String REASON = "reason";
        public static final String LEAVE_LOCATION = "leave_location";
        public static final String STATUS = "status";
    }

    public static class Location {

        public static final int SUCCESS_RESULT = 0;
        public static final int FAILURE_RESULT = 1;
        public static final String PACKAGE_NAME = "in.technitab.ess";
        public static final String RECEIVER = PACKAGE_NAME + ".RECEIVER";
        public static final String RESULT_DATA_KEY = PACKAGE_NAME + ".RESULT_DATA_KEY";
        public static final String LOCATION_DATA_EXTRA = PACKAGE_NAME + ".LOCATION_DATA_EXTRA";
        public static final String LOCATION = "location";
        public static final String LOCATION_ADDRESS = "location_address";
    }

    public class MIX_ID {
        public static final String VIEW_TYPE = "view_type";
        public static final String MONTH = "month";
        public static final String YEAR = "year";
        public static final String ACTION_VIEW_TYPE = "action_view_type";
        public static final String CREATED_BY_ID = "created_by_id";
        public static final String ACTION = "action";
        public static final String ADD = "add";
        public static final String VIEW = "view";
        public static final String VENDOR = "vendor";
        public static final String ID = "id";
        public static final String Status = "Status";
        public static final String PROJECT_ID = "project_id";
        public static final String APPROVE = "approve";
        public static final String SUBMIT = "submit";
        public static final String UPDATE = "update";
        public static final String HEADER_POSITION = "header_position";
        public static final String TITLE = "title";
        public static final String TRIP = "trip";
        public static final String VALUE = "value";
        public static final String DELETE = "delete";
        public static final String INSERT = "insert";
        public static final String BOOKING_ID = "booking_id";
        public static final String MODIFIED_BY_ID = "modified_by_id";
        public static final String USER_NAME = "user_name";
        public static final String PROJECT = "project";
    }

    public class Timesheet {
        public static final String STAFF_NAME = "staff_name";
        public static final String DATE = "date";
        public static final String PROJECT_JSON = "project_json";
    }

    public class Tbl_TimeSheet {
        public static final String PROJECT_ID = "project_id";
        public static final String DATE = "date";
        public static final String ACTIVITY_TYPE_ID = "activity_type_id";
        public static final String PROJECT = "project";
        public static final String ACTIVITY = "activity";
        public static final String TIME_SPENT = "time_spent";
        public static final String DESCRIPTION = "description";
        public static final String PROJECT_TYPE_ID = "project_type_id";
        public static final String ACTIVITY_ID = "activity_id";
        public static final String IS_BILLABLE = "is_billable";
    }

    public class Project {
        public static final String ID = "id";
        public static final String PROJECT_NAME = "project_name";
        public static final String PROJECT_TYPE_ID = "project_type_id";
        public static final String SITE_LOCATION = "site_location";
        public static final String STATE = "state";
        public static final String DISTRICT = "district";
        public static final String COUNTRY = "country";
    }

    public class UserProfile {
        public static final String NAME = "name";
        public static final String DESIGNATION = "designation";
        public static final String EMERGENCY_NUMBER = "emergency_number";
        public static final String MOBILE_NUMBER = "mobile_number";
        public static final String OFFICIAL_EMAIL_ID = "official_email_id";
        public static final String PERSONAL_EMAIL_ID = "personal_email_id";
        public static final String CURRENT_FULL_ADDRES = "current_full_addres";
        public static final String PERMANENT_FULL_ADDRESS = "permanent_full_address";
        public static final String BLOOD_GROUP = "blood_group";
        public static final String BIRTH_DATE = "birth_date";
        public static final String MARITAL_STATUS = "marital_status";
        public static final String MARRIAGE_DATE = "marriage_date";
        public static final String FATHER = "father";
        public static final String SPOUSE = "spouse";
        public static final String NATIONALITY = "nationality";
        public static final String RELIGION = "religion";
        public static final String GENDER = "gender";
        public static final String BASE_OFFICE_LOCATION = "base_office_location";
        public static final String REPORTING_TO = "reporting_to";
        public static final String JOINING_DATE = "joining_date";
        public static final String APPOINTMENT_DATE = "appointment_date";
        public static final String PAN_NUMBER = "pan_number";
        public static final String PASSPORT_NUMBER = "passport_number";
        public static final String AADHAR_NUMBER = "aadhar_number";
        public static final String DRIVING_LICENSE_NUMBER = "driving_license_number";
        public static final String VOTER_ID_NUMBER = "voter_id_number";
        public static final String BANK_NAME = "bank_name";
        public static final String BANK_ADDRESS = "bank_address";
        public static final String ACCOUNT_NUMER = "account_numer";
        public static final String IFSC_CODE = "ifsc_code";
        public static final String TENTH_YEAR = "10th_year";
        public static final String TENTH_SCHOOL = "10th_school";
        public static final String TENTH_BOARD = "10th_board";
        public static final String TENTH_PERCENTAGE = "10th_percentage";
        public static final String TWELVE_YEAR = "12th_year";
        public static final String TWELVE_SCHOOL = "12th_school";
        public static final String TWELVE_BOARD = "12th_board";
        public static final String TWELVE_PERCENTAGE = "12th_percentage";
        public static final String DIPLOMA_YEAR = "diploma_year";
        public static final String DIPLOMA_SCHOOL = "diploma_school";
        public static final String DIPLOMA_BOARD = "diploma_board";
        public static final String DIPLOMA_PERCENTAGE = "diploma_percentage";
        public static final String GRAD_YEAR = "grad_year";
        public static final String GRAD_SCHOOL = "grad_school";
        public static final String GRAD_BOARD = "grad_board";
        public static final String GRAD_PERCENTAGE = "grad_percentage";
        public static final String POST_GRAD_YEAR = "post_grad_year";
        public static final String POST_GRAD_SCHOOL = "post_grad_school";
        public static final String POST_GRAD_BOARD = "post_grad_board";
        public static final String POST_GRAD_PERCENTAGE = "post_grad_percentage";
        public static final String IMAGE_PATH = "image_path";
    }


    public static class Tec {
        public static final String ID = "id";
        public static final String PROJECT_ID = "project_id";
        public static final String CLAIM_START_DATE = "claim_start_date";
        public static final String CLAIM_END_DATE = "claim_end_date";
        public static final String BASE_LOCATION = "base_location";
        public static final String SITE_LOCATION = "site_location";
        public static final String STATUS = "status";
        public static final String TOTAL_AMOUNT = "total_amount";
        public static final String DESCRIPTION = "description";
        public static final String CREATED_BY_ID = "created_by_id";
        public static final String PROJECT_NAME = "project_name";
        public static final String CREATED_DATE = "created_date";
        public static final String USER_NOTE = "user_note";
        public static final String SUBMIT_BY_ID = "submit_by_id";
        public static final String MODIFIED_BY_ID = "modified_by_id";
        public static final String MODIFIED_DATE = "modified_date";
        public static final String SUBMIT_DATE = "submit_date";
        public static final String REMARK = "remark";
        public static final String BOOKING_ID = "booking_id";
        public static final String PAYMENT_ID = "payment_id";
        public static final String TEC_ID = "tec_id";
        public static final String ENTRY_CATEGORY = "entry_category";
        public static final String TRAVEL_MODE = "travel_mode";
        public static final String DEPARTURE_DATE = "deprt_date";
        public static final String DEPARTURE_TIME = "deprt_time";
        public static final String ARRIVAL_DATE = "arrival_date";
        public static final String ARRIVAL_TIME = "arrival_time";
        public static final String LOCATION = "location";
        public static final String FROM_LOCATION = "from_location";
        public static final String TO_LOCATION = "to_location";
        public static final String KILO_METER = "kilo_meter";
        public static final String MILEAGE = "mileage";
        public static final String UNIT_PRICE = "unit_price";
        public static final String VENDOR = "vendor";
        public static final String TOTAL_QUANTITTY = "total_quantitty";
        public static final String NON_WORKING_DAYS = "Non_working_days";
        public static final String DATE = "date";
        public static final String PAID_TO = "paid_to";
        public static final String PAID_BY = "paid_by";
        public static final String GSTIN = "gstin";
        public static final String BILL_AMOUNT = "bill_amount";
        public static final String BILL_NUM = "bill_num";
        public static final String ATTACHMENT_PATH = "attachment_path";
        public static final String ENTRY_ID = "entry_id";
        public static final String TRAVEL_DATE = "travel_date";
        public static final String CLAIM_DATE = "claim_date";
        public static final String CITY_VALUE = "is_metro";
        public static final String IS_BILLABLE = "is_billable";
        public static final String PAID_TO_ID = "paid_to_id";
        public static final String IS_INTERNATIONAL = "is_international";
        public static final String TEC_JSON = "tec_json";
        public static final String TRIP_ID = "trip_id";
    }


    public static class Trip {
        public static final String TRIP_ID = "id";
        public static final String PROJECT_ID = "project_id";
        public static final String PROJECT_NAME = "project_name";
        public static final String SOURCE = "source";
        public static final String DESTINATION = "destination";
        public static final String START_DATE = "start_date";
        public static final String MEMBER_JSON = "member_json";
        public static final String STATUS = "status";
        public static final String REMARK = "remark";
        public static final String COMMENT = "comment";
        public static final String CREATED_DATE = "created_date";
        public static final String CREATED_BY_ID = "created_by_id";
        public static final String CREATED_BY = "created_by";
        public static final String END_DATE = "end_date";
    }


    public static class TripBooking {
        public final static String ID = "id";
        public final static String TRIP_ID = "trip_id";
        public final static String TRAVEL_TYPE = "travel_type";
        public final static String USER_BOOKING_MODE = "user_booking_mode";
        public final static String USER_RATE = "user_rate";
        public final static String USER_CITY_AREA = "user_city_area";
        public final static String USER_VENDOR = "user_vendor";
        public final static String USER_SOURCE = "user_source";
        public final static String USER_VENDOR_ID = "user_vendor_id";
        public final static String USER_DESTINATION = "user_destination";
        public final static String USER_TRAVEL_DATE = "user_travel_date";
        public final static String USER_INSTRUCTION = "user_instruction";
        public final static String USER_CHECK_IN = "user_check_in";
        public final static String USER_CHECK_OUT = "user_check_out";
        public final static String USER_ROOM = "user_room";
        public final static String USER_TOTAL_AMOUNT = "user_total_amount";
        public final static String ADMIN_BOOKING_MODE = "admin_booking_mode";
        public final static String ADMIN_CITY_AREA = "admin_city_area";
        public final static String ADMIN_VENDOR = "admin_vendor";
        public final static String ADMIN_VENDOR_ID = "admin_vendor_id";
        public final static String ADMIN_SOURCE = "admin_source";
        public final static String ADMIN_DESTINATION = "admin_destination";
        public final static String ADMIN_INSTRUCTION = "admin_instruction";
        public final static String ADMIN_CHECK_IN = "admin_check_in";
        public final static String ADMIN_CHECK_OUT = "admin_check_out";
        public final static String ADMIN_ROOM = "admin_room";
        public final static String ADMIN_TOTAL_AMOUNT = "admin_total_amount";
        public final static String ADMIN_DEPARTURE_DATE_TIME = "admin_departure_date_time";
        public final static String ADMIN_ARRIVAL_DATE_TIME = "admin_arrival_date_time";
        public final static String TAX_NAME = "tax_name";
        public final static String TAX_AMOUNT = "tax_amount";
        public final static String TAX_TYPE = "tax_type";
        public final static String SERVICE_TAX_NAME = "service_tax_name";
        public final static String SERVICE_TAX_PERCENT = "service_tax_percent";
        public final static String SERVICE_TAX_AMOUNT = "service_tax_amount";
        public final static String SERVICE_TAX_TYPE = "service_tax_type";
        public final static String TOTAL_AMOUNT = "total_amount";
        public final static String ADMIN_BOOKING_ATTACHMENT = "admin_booking_attachment";
        public final static String TRIP_BOOKING_MEMBER = "trip_booking_member";
        public final static String TRIP_STATUS = "trip_status";
        public final static String CREATED_BY_ID = "created_by_id";
        public final static String CREATED_DATE = "created_date";
        public final static String MODIFIED_BY_ID = "modified_by_id";
        public final static String MODIFIED_DATE = "modified_date";
        public final static String BILL_DATE = "Bill Date";
        public final static String BILL_ID = "Bill ID";
        public final static String BILL_NUMBER = "Bill Number";
        public final static String PURCHASE_ORDER = "PurchaseOrder";
        public final static String BILL_STATUS = "Bill Status";
        public final static String DESTINATION_OF_SUPPLY = "Destination of Supply";
        public final static String GST_TEATMENT = "GST Treatment";
        public final static String GST_NUM = "GST Identification Number (GSTIN)";
        public final static String VENDOR_NAME = "Vendor Name";
        public final static String DUE_DATE = "Due Date";
        public final static String CURRENCY_CODE = "Currency Code";
        public final static String ITEM_NAME = "Item Name";
        public final static String ACCOUNT = "Account";
        public final static String ITEM_DESCRIPTION = "Item Description";
        public final static String QUANTITY = "quantity";
        public final static String USAGE_UNIT = "Usage unit";
        public final static String RATE = "rate";
        public final static String TAX_PERCENTAGE = "Tax Percentage";
        public final static String ITEM_TOTAL = "Item Total";
        public final static String SUB_TOTAL = "SubTotal";
        public final static String TOTAL = "Total";
        public final static String PROJECT_NAME = "Project Name";
        public static final String BOOKING_REQUESTED_STATUS = "Booking Requested";
        public static final String BOOKING_DONE_STATUS = "Booking Done";
        public static final String PAYMENT_REQUESTED_STATUS = "Payment Requested";
        public static final String PAYMENT_DONE_STATUS = "PAYMENT Done";
        public static final String CANCELLATION_REQUESTED_STATUS = "Cancellation Requested";
        public static final String CANCELLATION_DONE_STATUS = "Cancellation Done";
        public static final String CREATE_BY = "created_by";
        public static final String PAYMENT_ID = "payment_id";
        public static final String PAID_BY = "paid_by";
    }

    public static class Value {
        public static ArrayList<String> getList(String state) {

            ArrayList<State> list = GenericList();
            ArrayList<String> districtList = new ArrayList<>();
            for (State s : list)
                if (state.equalsIgnoreCase(s.getCode())) {
                    districtList.add(s.getName());
                }
            return districtList;
        }


        public static ArrayList<String> getDistrictList() {
            ArrayList<State> list = GenericList();
            ArrayList<String> districtList = new ArrayList<>();
            for (State s : list)
                if (!districtList.contains(s.getCode())) {
                    districtList.add(s.getName());
                }

            return districtList;
        }

        public static ArrayList<BookingMode> getTripBookingMode() {
            ArrayList<BookingMode> models = new ArrayList<>();
            models.add(new BookingMode("Hotel/PG/Lodge", "Hotel"));
            models.add(new BookingMode("Guesthouse", "Guesthouse"));
            models.add(new BookingMode("Train", "Travel"));
            models.add(new BookingMode("Flight", "Travel"));
            models.add(new BookingMode("Bus", "Travel"));
            return models;
        }


        public static ArrayList<BookingMode> getPaymentTerm() {
            ArrayList<BookingMode> models = new ArrayList<>();
            models.add(new BookingMode("Due on Receipt", "0"));
            models.add(new BookingMode("Net 30", "30"));
            models.add(new BookingMode("Net 15", "15"));
            models.add(new BookingMode("Net 45", "45"));
            models.add(new BookingMode("Net 60", "60"));
            models.add(new BookingMode("Due end of the month", "-2"));
            models.add(new BookingMode("Due end of the next month", "-3"));
            return models;
        }

        public static ArrayList<BookingMode> getIGSTTaxPercent() {
            ArrayList<BookingMode> models = new ArrayList<>();
            models.add(new BookingMode("Non-Taxable", "", "", ""));
            models.add(new BookingMode("Out of scope", "", "", "5"));
            models.add(new BookingMode("Non-GST Supply", "", "", "4"));
            models.add(new BookingMode("IGST0 [0%]", "0", "ItemAmount", "eligible"));
            models.add(new BookingMode("IGST5 [5%]", "5", "ItemAmount", "eligible"));
            models.add(new BookingMode("IGST5 [12%]", "12", "ItemAmount", "eligible"));
            models.add(new BookingMode("IGST5 [18%]", "18", "ItemAmount", "eligible"));
            models.add(new BookingMode("IGST5 [28%]", "28", "ItemAmount", "eligible"));

            return models;
        }

        public static ArrayList<BookingMode> getGSTTaxPercent() {
            ArrayList<BookingMode> models = new ArrayList<>();
            models.add(new BookingMode("Non-Taxable", "", "", ""));
            models.add(new BookingMode("Out of scope", "", "", "5"));
            models.add(new BookingMode("Non-GST Supply", "", "", "4"));
            models.add(new BookingMode("GST0 [0%]", "0", "Tax Group", "eligible"));
            models.add(new BookingMode("GST5 [5%]", "5", "Tax Group", "eligible"));
            models.add(new BookingMode("GST5 [12%]", "12", "Tax Group", "eligible"));
            models.add(new BookingMode("GST5 [18%]", "18", "Tax Group", "eligible"));
            models.add(new BookingMode("GST5 [28%]", "28", "Tax Group", "eligible"));

            return models;
        }

        private static ArrayList<State> GenericList() {
            ArrayList<State> list = new ArrayList<>();
            list.add(new State("Andaman And Nicobar Islands", "Nicobars"));
            list.add(new State("Andaman And Nicobar Islands", "North & Middle Andaman"));
            list.add(new State("Andaman And Nicobar Islands", "South Andaman"));
            list.add(new State("Andhra Pradesh", "Anantapur"));
            list.add(new State("Andhra Pradesh", "Chittoor"));
            list.add(new State("Andhra Pradesh", "East Godavari"));
            list.add(new State("Andhra Pradesh", "Guntur"));
            list.add(new State("Andhra Pradesh", "Krishna"));
            list.add(new State("Andhra Pradesh", "Kurnool"));
            list.add(new State("Andhra Pradesh", "Prakasam"));
            list.add(new State("Andhra Pradesh", "Sri Potti Sriramulu Nellore"));
            list.add(new State("Andhra Pradesh", "Srikakulam"));
            list.add(new State("Andhra Pradesh", "Visakhapatnam"));
            list.add(new State("Andhra Pradesh", "Vizianagaram"));
            list.add(new State("Andhra Pradesh", "West Godavari"));
            list.add(new State("Andhra Pradesh", "Y.S.R."));
            list.add(new State("Arunachal Pradesh", "Anjaw"));
            list.add(new State("Arunachal Pradesh", "Changlang"));
            list.add(new State("Arunachal Pradesh", "Dibang Valley"));
            list.add(new State("Arunachal Pradesh", "East Kameng"));
            list.add(new State("Arunachal Pradesh", "East Siang"));
            list.add(new State("Arunachal Pradesh", "Kurung Kumey"));
            list.add(new State("Arunachal Pradesh", "Lohit"));
            list.add(new State("Arunachal Pradesh", "Lower Dibang Valley"));
            list.add(new State("Arunachal Pradesh", "Lower Subansiri"));
            list.add(new State("Arunachal Pradesh", "Papumpare"));
            list.add(new State("Arunachal Pradesh", "Tawang"));
            list.add(new State("Arunachal Pradesh", "Tirap"));
            list.add(new State("Arunachal Pradesh", "Upper Siang"));
            list.add(new State("Arunachal Pradesh", "Upper Subansiri"));
            list.add(new State("Arunachal Pradesh", "West Kameng"));
            list.add(new State("Arunachal Pradesh", "West Siang"));
            list.add(new State("Assam", "Baksa"));
            list.add(new State("Assam", "Barpeta"));
            list.add(new State("Assam", "Bongaigaon"));
            list.add(new State("Assam", "Cachar"));
            list.add(new State("Assam", "Chirang"));
            list.add(new State("Assam", "Darrang"));
            list.add(new State("Assam", "Dhemaji"));
            list.add(new State("Assam", "Dhubri"));
            list.add(new State("Assam", "Dibrugarh"));
            list.add(new State("Assam", "Dima Hasao"));
            list.add(new State("Assam", "Goalpara"));
            list.add(new State("Assam", "Golaghat"));
            list.add(new State("Assam", "Hailakandi"));
            list.add(new State("Assam", "Jorhat"));
            list.add(new State("Assam", "Kamrup"));
            list.add(new State("Assam", "Kamrup Metropolitan"));
            list.add(new State("Assam", "Karbi Anglong"));
            list.add(new State("Assam", "Karimganj"));
            list.add(new State("Assam", "Kokrajhar"));
            list.add(new State("Assam", "Lakhimpur"));
            list.add(new State("Assam", "Morigaon"));
            list.add(new State("Assam", "Nagaon"));
            list.add(new State("Assam", "Nalbari"));
            list.add(new State("Assam", "Sivasagar"));
            list.add(new State("Assam", "Sonitpur"));
            list.add(new State("Assam", "Tinsukia"));
            list.add(new State("Assam", "Udalguri"));
            list.add(new State("Bihar", "Araria"));
            list.add(new State("Bihar", "Arwal"));
            list.add(new State("Bihar", "Aurangabad"));
            list.add(new State("Bihar", "Banka"));
            list.add(new State("Bihar", "Begusarai"));
            list.add(new State("Bihar", "Bhagalpur"));
            list.add(new State("Bihar", "Bhojpur"));
            list.add(new State("Bihar", "Buxar"));
            list.add(new State("Bihar", "Darbhanga"));
            list.add(new State("Bihar", "Gaya"));
            list.add(new State("Bihar", "Gopalganj"));
            list.add(new State("Bihar", "Jamui"));
            list.add(new State("Bihar", "Jehanabad"));
            list.add(new State("Bihar", "Kaimur (Bhabua)"));
            list.add(new State("Bihar", "Katihar"));
            list.add(new State("Bihar", "Khagaria"));
            list.add(new State("Bihar", "Kishanganj"));
            list.add(new State("Bihar", "Lakhisarai"));
            list.add(new State("Bihar", "Madhepura"));
            list.add(new State("Bihar", "Madhubani"));
            list.add(new State("Bihar", "Munger"));
            list.add(new State("Bihar", "Muzaffarpur"));
            list.add(new State("Bihar", "Nalanda"));
            list.add(new State("Bihar", "Nawada"));
            list.add(new State("Bihar", "Pashchim Champaran"));
            list.add(new State("Bihar", "Patna"));
            list.add(new State("Bihar", "Purba Champaran"));
            list.add(new State("Bihar", "Purnia"));
            list.add(new State("Bihar", "Rohtas"));
            list.add(new State("Bihar", "Saharsa"));
            list.add(new State("Bihar", "Samastipur"));
            list.add(new State("Bihar", "Saran"));
            list.add(new State("Bihar", "Sheikhpura"));
            list.add(new State("Bihar", "Sheohar"));
            list.add(new State("Bihar", "Sitamarhi"));
            list.add(new State("Bihar", "Siwan"));
            list.add(new State("Bihar", "Supaul"));
            list.add(new State("Bihar", "Vaishali"));
            list.add(new State("Chandigarh", "Chandigarh"));
            list.add(new State("Chhattisgarh", "Bastar"));
            list.add(new State("Chhattisgarh", "Bijapur"));
            list.add(new State("Chhattisgarh", "Bilaspur"));
            list.add(new State("Chhattisgarh", "Dakshin Bastar Dantewada"));
            list.add(new State("Chhattisgarh", "Dhamtari"));
            list.add(new State("Chhattisgarh", "Durg"));
            list.add(new State("Chhattisgarh", "Janjgir - Champa"));
            list.add(new State("Chhattisgarh", "Jashpur"));
            list.add(new State("Chhattisgarh", "Kabirdham"));
            list.add(new State("Chhattisgarh", "Korba"));
            list.add(new State("Chhattisgarh", "Korea (Koriya)"));
            list.add(new State("Chhattisgarh", "Mahasamund"));
            list.add(new State("Chhattisgarh", "Narayanpur"));
            list.add(new State("Chhattisgarh", "Raigarh"));
            list.add(new State("Chhattisgarh", "Raipur"));
            list.add(new State("Chhattisgarh", "Rajnandgaon"));
            list.add(new State("Chhattisgarh", "Surguja"));
            list.add(new State("Chhattisgarh", "Uttar Bastar Kanker"));
            list.add(new State("Dadra And Nagar Haveli", "Dadra & Nagar Haveli"));
            list.add(new State("Daman And Diu", "Daman"));
            list.add(new State("Daman And Diu", "Diu"));
            list.add(new State("Delhi", "Central"));
            list.add(new State("Delhi", "East"));
            list.add(new State("Delhi", "New Delhi"));
            list.add(new State("Delhi", "North"));
            list.add(new State("Delhi", "North East"));
            list.add(new State("Delhi", "North West"));
            list.add(new State("Delhi", "South"));
            list.add(new State("Delhi", "South West"));
            list.add(new State("Delhi", "West"));
            list.add(new State("Goa", "North Goa"));
            list.add(new State("Goa", "South Goa"));
            list.add(new State("Gujarat", "Ahmadabad"));
            list.add(new State("Gujarat", "Amreli"));
            list.add(new State("Gujarat", "Anand"));
            list.add(new State("Gujarat", "Banaskantha"));
            list.add(new State("Gujarat", "Bharuch"));
            list.add(new State("Gujarat", "Bhavnagar"));
            list.add(new State("Gujarat", "Dohad"));
            list.add(new State("Gujarat", "Gandhinagar"));
            list.add(new State("Gujarat", "Jamnagar"));
            list.add(new State("Gujarat", "Junagadh"));
            list.add(new State("Gujarat", "Kachchh"));
            list.add(new State("Gujarat", "Kheda"));
            list.add(new State("Gujarat", "Mahesana"));
            list.add(new State("Gujarat", "Narmada"));
            list.add(new State("Gujarat", "Navsari"));
            list.add(new State("Gujarat", "Panchmahal"));
            list.add(new State("Gujarat", "Patan"));
            list.add(new State("Gujarat", "Porbandar"));
            list.add(new State("Gujarat", "Rajkot"));
            list.add(new State("Gujarat", "Sabarkantha"));
            list.add(new State("Gujarat", "Surat"));
            list.add(new State("Gujarat", "Surendranagar"));
            list.add(new State("Gujarat", "Tapi"));
            list.add(new State("Gujarat", "The Dangs"));
            list.add(new State("Gujarat", "Vadodara"));
            list.add(new State("Gujarat", "Valsad"));
            list.add(new State("Haryana", "Ambala"));
            list.add(new State("Haryana", "Bhiwani"));
            list.add(new State("Haryana", "Faridabad"));
            list.add(new State("Haryana", "Fatehabad"));
            list.add(new State("Haryana", "Gurgaon"));
            list.add(new State("Haryana", "Hisar"));
            list.add(new State("Haryana", "Jhajjar"));
            list.add(new State("Haryana", "Jind"));
            list.add(new State("Haryana", "Kaithal"));
            list.add(new State("Haryana", "Karnal"));
            list.add(new State("Haryana", "Kurukshetra"));
            list.add(new State("Haryana", "Mahendragarh"));
            list.add(new State("Haryana", "Mewat"));
            list.add(new State("Haryana", "Palwal"));
            list.add(new State("Haryana", "Panchkula"));
            list.add(new State("Haryana", "Panipat"));
            list.add(new State("Haryana", "Rewari"));
            list.add(new State("Haryana", "Rohtak"));
            list.add(new State("Haryana", "Sirsa"));
            list.add(new State("Haryana", "Sonipat"));
            list.add(new State("Haryana", "Yamunanagar"));
            list.add(new State("Himachal Pradesh", "Bilaspur"));
            list.add(new State("Himachal Pradesh", "Chamba"));
            list.add(new State("Himachal Pradesh", "Hamirpur"));
            list.add(new State("Himachal Pradesh", "Kangra"));
            list.add(new State("Himachal Pradesh", "Kinnaur"));
            list.add(new State("Himachal Pradesh", "Kullu"));
            list.add(new State("Himachal Pradesh", "Lahul And Spiti"));
            list.add(new State("Himachal Pradesh", "Mandi"));
            list.add(new State("Himachal Pradesh", "Shimla"));
            list.add(new State("Himachal Pradesh", "Sirmaur"));
            list.add(new State("Himachal Pradesh", "Solan"));
            list.add(new State("Himachal Pradesh", "Una"));
            list.add(new State("Jammu And Kashmir", "Anantnag"));
            list.add(new State("Jammu And Kashmir", "Badgam"));
            list.add(new State("Jammu And Kashmir", "Bandipore"));
            list.add(new State("Jammu And Kashmir", "Baramula"));
            list.add(new State("Jammu And Kashmir", "Doda"));
            list.add(new State("Jammu And Kashmir", "Ganderbal"));
            list.add(new State("Jammu And Kashmir", "Jammu"));
            list.add(new State("Jammu And Kashmir", "Kargil"));
            list.add(new State("Jammu And Kashmir", "Kathua"));
            list.add(new State("Jammu And Kashmir", "Kishtwar"));
            list.add(new State("Jammu And Kashmir", "Kulgam"));
            list.add(new State("Jammu And Kashmir", "Kupwara"));
            list.add(new State("Jammu And Kashmir", "Leh"));
            list.add(new State("Jammu And Kashmir", "Pulwama"));
            list.add(new State("Jammu And Kashmir", "Punch"));
            list.add(new State("Jammu And Kashmir", "Rajouri"));
            list.add(new State("Jammu And Kashmir", "Ramban"));
            list.add(new State("Jammu And Kashmir", "Reasi"));
            list.add(new State("Jammu And Kashmir", "Samba"));
            list.add(new State("Jammu And Kashmir", "Shupiyan"));
            list.add(new State("Jammu And Kashmir", "Srinagar"));
            list.add(new State("Jammu And Kashmir", "Udhampur"));
            list.add(new State("Jharkhand", "Bokaro"));
            list.add(new State("Jharkhand", "Chatra"));
            list.add(new State("Jharkhand", "Deoghar"));
            list.add(new State("Jharkhand", "Dhanbad"));
            list.add(new State("Jharkhand", "Dumka"));
            list.add(new State("Jharkhand", "Garhwa"));
            list.add(new State("Jharkhand", "Giridih"));
            list.add(new State("Jharkhand", "Godda"));
            list.add(new State("Jharkhand", "Gumla"));
            list.add(new State("Jharkhand", "Hazaribagh"));
            list.add(new State("Jharkhand", "Jamtara"));
            list.add(new State("Jharkhand", "Khunti"));
            list.add(new State("Jharkhand", "Kodarma"));
            list.add(new State("Jharkhand", "Latehar"));
            list.add(new State("Jharkhand", "Lohardaga"));
            list.add(new State("Jharkhand", "Pakur"));
            list.add(new State("Jharkhand", "Palamu"));
            list.add(new State("Jharkhand", "Pashchimi Singhbhum"));
            list.add(new State("Jharkhand", "Purbi Singhbhum"));
            list.add(new State("Jharkhand", "Ramgarh"));
            list.add(new State("Jharkhand", "Ranchi"));
            list.add(new State("Jharkhand", "Sahibganj"));
            list.add(new State("Jharkhand", "Saraikela Kharsawan"));
            list.add(new State("Jharkhand", "Simdega"));
            list.add(new State("Karnataka", "Bagalkot"));
            list.add(new State("Karnataka", "Bangalore"));
            list.add(new State("Karnataka", "Bangalore Rural"));
            list.add(new State("Karnataka", "Belgaum"));
            list.add(new State("Karnataka", "Bellary"));
            list.add(new State("Karnataka", "Bidar"));
            list.add(new State("Karnataka", "Bijapur"));
            list.add(new State("Karnataka", "Chamarajanagar"));
            list.add(new State("Karnataka", "Chikkaballapura"));
            list.add(new State("Karnataka", "Chikmagalur"));
            list.add(new State("Karnataka", "Chitradurga"));
            list.add(new State("Karnataka", "Dakshina Kannada"));
            list.add(new State("Karnataka", "Davanagere"));
            list.add(new State("Karnataka", "Dharwad"));
            list.add(new State("Karnataka", "Gadag"));
            list.add(new State("Karnataka", "Gulbarga"));
            list.add(new State("Karnataka", "Hassan"));
            list.add(new State("Karnataka", "Haveri"));
            list.add(new State("Karnataka", "Kodagu"));
            list.add(new State("Karnataka", "Kolar"));
            list.add(new State("Karnataka", "Koppal"));
            list.add(new State("Karnataka", "Mandya"));
            list.add(new State("Karnataka", "Mysore"));
            list.add(new State("Karnataka", "Raichur"));
            list.add(new State("Karnataka", "Ramanagara"));
            list.add(new State("Karnataka", "Shimoga"));
            list.add(new State("Karnataka", "Tumkur"));
            list.add(new State("Karnataka", "Udupi"));
            list.add(new State("Karnataka", "Uttara Kannada"));
            list.add(new State("Karnataka", "Yadgir"));
            list.add(new State("Kerala", "Alappuzha"));
            list.add(new State("Kerala", "Ernakulam"));
            list.add(new State("Kerala", "Idukki"));
            list.add(new State("Kerala", "Kannur"));
            list.add(new State("Kerala", "Kasaragod"));
            list.add(new State("Kerala", "Kollam"));
            list.add(new State("Kerala", "Kottayam"));
            list.add(new State("Kerala", "Kozhikode"));
            list.add(new State("Kerala", "Malappuram"));
            list.add(new State("Kerala", "Palakkad"));
            list.add(new State("Kerala", "Pathanamthitta"));
            list.add(new State("Kerala", "Thiruvananthapuram"));
            list.add(new State("Kerala", "Thrissur"));
            list.add(new State("Kerala", "Wayanad"));
            list.add(new State("Lakshadweep", "Lakshadweep"));
            list.add(new State("Madhya Pradesh", "Alirajpur"));
            list.add(new State("Madhya Pradesh", "Anuppur"));
            list.add(new State("Madhya Pradesh", "Ashoknagar"));
            list.add(new State("Madhya Pradesh", "Balaghat"));
            list.add(new State("Madhya Pradesh", "Barwani"));
            list.add(new State("Madhya Pradesh", "Betul"));
            list.add(new State("Madhya Pradesh", "Bhind"));
            list.add(new State("Madhya Pradesh", "Bhopal"));
            list.add(new State("Madhya Pradesh", "Burhanpur"));
            list.add(new State("Madhya Pradesh", "Chhatarpur"));
            list.add(new State("Madhya Pradesh", "Chhindwara"));
            list.add(new State("Madhya Pradesh", "Damoh"));
            list.add(new State("Madhya Pradesh", "Datia"));
            list.add(new State("Madhya Pradesh", "Dewas"));
            list.add(new State("Madhya Pradesh", "Dhar"));
            list.add(new State("Madhya Pradesh", "Dindori"));
            list.add(new State("Madhya Pradesh", "Guna"));
            list.add(new State("Madhya Pradesh", "Gwalior"));
            list.add(new State("Madhya Pradesh", "Harda"));
            list.add(new State("Madhya Pradesh", "Hoshangabad"));
            list.add(new State("Madhya Pradesh", "Indore"));
            list.add(new State("Madhya Pradesh", "Jabalpur"));
            list.add(new State("Madhya Pradesh", "Jhabua"));
            list.add(new State("Madhya Pradesh", "Katni"));
            list.add(new State("Madhya Pradesh", "Khandwa (East Nimar)"));
            list.add(new State("Madhya Pradesh", "Khargone (West Nimar)"));
            list.add(new State("Madhya Pradesh", "Mandla"));
            list.add(new State("Madhya Pradesh", "Mandsaur"));
            list.add(new State("Madhya Pradesh", "Morena"));
            list.add(new State("Madhya Pradesh", "Narsimhapur"));
            list.add(new State("Madhya Pradesh", "Neemuch"));
            list.add(new State("Madhya Pradesh", "Panna"));
            list.add(new State("Madhya Pradesh", "Raisen"));
            list.add(new State("Madhya Pradesh", "Rajgarh"));
            list.add(new State("Madhya Pradesh", "Ratlam"));
            list.add(new State("Madhya Pradesh", "Rewa"));
            list.add(new State("Madhya Pradesh", "Sagar"));
            list.add(new State("Madhya Pradesh", "Satna"));
            list.add(new State("Madhya Pradesh", "Sehore"));
            list.add(new State("Madhya Pradesh", "Seoni"));
            list.add(new State("Madhya Pradesh", "Shahdol"));
            list.add(new State("Madhya Pradesh", "Shajapur"));
            list.add(new State("Madhya Pradesh", "Sheopur"));
            list.add(new State("Madhya Pradesh", "Shivpuri"));
            list.add(new State("Madhya Pradesh", "Sidhi"));
            list.add(new State("Madhya Pradesh", "Singrauli"));
            list.add(new State("Madhya Pradesh", "Tikamgarh"));
            list.add(new State("Madhya Pradesh", "Ujjain"));
            list.add(new State("Madhya Pradesh", "Umaria"));
            list.add(new State("Madhya Pradesh", "Vidisha"));
            list.add(new State("Maharashtra", "Ahmadnagar"));
            list.add(new State("Maharashtra", "Akola"));
            list.add(new State("Maharashtra", "Amravati"));
            list.add(new State("Maharashtra", "Aurangabad"));
            list.add(new State("Maharashtra", "Bhandara"));
            list.add(new State("Maharashtra", "Bid"));
            list.add(new State("Maharashtra", "Buldana"));
            list.add(new State("Maharashtra", "Chandrapur"));
            list.add(new State("Maharashtra", "Dhule"));
            list.add(new State("Maharashtra", "Gadchiroli"));
            list.add(new State("Maharashtra", "Gondiya"));
            list.add(new State("Maharashtra", "Hingoli"));
            list.add(new State("Maharashtra", "Jalgaon"));
            list.add(new State("Maharashtra", "Jalna"));
            list.add(new State("Maharashtra", "Kolhapur"));
            list.add(new State("Maharashtra", "Latur"));
            list.add(new State("Maharashtra", "Mumbai"));
            list.add(new State("Maharashtra", "Mumbai Suburban"));
            list.add(new State("Maharashtra", "Nagpur"));
            list.add(new State("Maharashtra", "Nanded"));
            list.add(new State("Maharashtra", "Nandurbar"));
            list.add(new State("Maharashtra", "Nashik"));
            list.add(new State("Maharashtra", "Osmanabad"));
            list.add(new State("Maharashtra", "Parbhani"));
            list.add(new State("Maharashtra", "Pune"));
            list.add(new State("Maharashtra", "Raigarh"));
            list.add(new State("Maharashtra", "Ratnagiri"));
            list.add(new State("Maharashtra", "Sangli"));
            list.add(new State("Maharashtra", "Satara"));
            list.add(new State("Maharashtra", "Sindhudurg"));
            list.add(new State("Maharashtra", "Solapur"));
            list.add(new State("Maharashtra", "Thane"));
            list.add(new State("Maharashtra", "Wardha"));
            list.add(new State("Maharashtra", "Washim"));
            list.add(new State("Maharashtra", "Yavatmal"));
            list.add(new State("Manipur", "Bishnupur"));
            list.add(new State("Manipur", "Chandel"));
            list.add(new State("Manipur", "Churachandpur"));
            list.add(new State("Manipur", "Imphal East"));
            list.add(new State("Manipur", "Imphal West"));
            list.add(new State("Manipur", "Senapati (Excluding 3 Sub-Divisions)"));
            list.add(new State("Manipur", "Tamenglong"));
            list.add(new State("Manipur", "Thoubal"));
            list.add(new State("Manipur", "Ukhrul"));
            list.add(new State("Meghalaya", "East Garo Hills"));
            list.add(new State("Meghalaya", "East Khasi Hills"));
            list.add(new State("Meghalaya", "Jaintia Hills"));
            list.add(new State("Meghalaya", "Ribhoi"));
            list.add(new State("Meghalaya", "South Garo Hills"));
            list.add(new State("Meghalaya", "West Garo Hills"));
            list.add(new State("Meghalaya", "West Khasi Hills"));
            list.add(new State("Mizoram", "Aizawl"));
            list.add(new State("Mizoram", "Champhai"));
            list.add(new State("Mizoram", "Kolasib"));
            list.add(new State("Mizoram", "Lawngtlai"));
            list.add(new State("Mizoram", "Lunglei"));
            list.add(new State("Mizoram", "Mamit"));
            list.add(new State("Mizoram", "Saiha"));
            list.add(new State("Mizoram", "Serchhip"));
            list.add(new State("Nagaland", "Dimapur"));
            list.add(new State("Nagaland", "Kiphire"));
            list.add(new State("Nagaland", "Kohima"));
            list.add(new State("Nagaland", "Longleng"));
            list.add(new State("Nagaland", "Mokokchung"));
            list.add(new State("Nagaland", "Mon"));
            list.add(new State("Nagaland", "Peren"));
            list.add(new State("Nagaland", "Phek"));
            list.add(new State("Nagaland", "Tuensang"));
            list.add(new State("Nagaland", "Wokha"));
            list.add(new State("Nagaland", "Zunheboto"));
            list.add(new State("Odisha", "Anugul"));
            list.add(new State("Odisha", "Balangir"));
            list.add(new State("Odisha", "Baleshwar"));
            list.add(new State("Odisha", "Bargarh"));
            list.add(new State("Odisha", "Baudh"));
            list.add(new State("Odisha", "Bhadrak"));
            list.add(new State("Odisha", "Cuttack"));
            list.add(new State("Odisha", "Debagarh"));
            list.add(new State("Odisha", "Dhenkanal"));
            list.add(new State("Odisha", "Gajapati"));
            list.add(new State("Odisha", "Ganjam"));
            list.add(new State("Odisha", "Jagatsinghapur"));
            list.add(new State("Odisha", "Jajapur"));
            list.add(new State("Odisha", "Jharsuguda"));
            list.add(new State("Odisha", "Kalahandi"));
            list.add(new State("Odisha", "Kandhamal"));
            list.add(new State("Odisha", "Kendrapara"));
            list.add(new State("Odisha", "Kendujhar"));
            list.add(new State("Odisha", "Khordha"));
            list.add(new State("Odisha", "Koraput"));
            list.add(new State("Odisha", "Malkangiri"));
            list.add(new State("Odisha", "Mayurbhanj"));
            list.add(new State("Odisha", "Nabarangapur"));
            list.add(new State("Odisha", "Nayagarh"));
            list.add(new State("Odisha", "Nuapada"));
            list.add(new State("Odisha", "Puri"));
            list.add(new State("Odisha", "Rayagada"));
            list.add(new State("Odisha", "Sambalpur"));
            list.add(new State("Odisha", "Subarnapur"));
            list.add(new State("Odisha", "Sundargarh"));
            list.add(new State("Puducherry", "Karaikal"));
            list.add(new State("Puducherry", "Mahe"));
            list.add(new State("Puducherry", "Puducherry"));
            list.add(new State("Puducherry", "Yanam"));
            list.add(new State("Punjab", "Amritsar"));
            list.add(new State("Punjab", "Barnala"));
            list.add(new State("Punjab", "Bathinda"));
            list.add(new State("Punjab", "Faridkot"));
            list.add(new State("Punjab", "Fatehgarh Sahib"));
            list.add(new State("Punjab", "Firozpur"));
            list.add(new State("Punjab", "Gurdaspur"));
            list.add(new State("Punjab", "Hoshiarpur"));
            list.add(new State("Punjab", "Jalandhar"));
            list.add(new State("Punjab", "Kapurthala"));
            list.add(new State("Punjab", "Ludhiana"));
            list.add(new State("Punjab", "Mansa"));
            list.add(new State("Punjab", "Moga"));
            list.add(new State("Punjab", "Muktsar"));
            list.add(new State("Punjab", "Patiala"));
            list.add(new State("Punjab", "Rupnagar"));
            list.add(new State("Punjab", "Sahibzada Ajit Singh Nagar"));
            list.add(new State("Punjab", "Sangrur"));
            list.add(new State("Punjab", "Shahid Bhagat Singh Nagar"));
            list.add(new State("Punjab", "Tarn Taran"));
            list.add(new State("Rajasthan", "Ajmer"));
            list.add(new State("Rajasthan", "Alwar"));
            list.add(new State("Rajasthan", "Banswara"));
            list.add(new State("Rajasthan", "Baran"));
            list.add(new State("Rajasthan", "Barmer"));
            list.add(new State("Rajasthan", "Bharatpur"));
            list.add(new State("Rajasthan", "Bhilwara"));
            list.add(new State("Rajasthan", "Bikaner"));
            list.add(new State("Rajasthan", "Bundi"));
            list.add(new State("Rajasthan", "Chittaurgarh"));
            list.add(new State("Rajasthan", "Churu"));
            list.add(new State("Rajasthan", "Dausa"));
            list.add(new State("Rajasthan", "Dhaulpur"));
            list.add(new State("Rajasthan", "Dungarpur"));
            list.add(new State("Rajasthan", "Ganganagar"));
            list.add(new State("Rajasthan", "Hanumangarh"));
            list.add(new State("Rajasthan", "Jaipur"));
            list.add(new State("Rajasthan", "Jaisalmer"));
            list.add(new State("Rajasthan", "Jalor"));
            list.add(new State("Rajasthan", "Jhalawar"));
            list.add(new State("Rajasthan", "Jhunjhunun"));
            list.add(new State("Rajasthan", "Jodhpur"));
            list.add(new State("Rajasthan", "Karauli"));
            list.add(new State("Rajasthan", "Kota"));
            list.add(new State("Rajasthan", "Nagaur"));
            list.add(new State("Rajasthan", "Pali"));
            list.add(new State("Rajasthan", "Pratapgarh"));
            list.add(new State("Rajasthan", "Rajsamand"));
            list.add(new State("Rajasthan", "Sawai Madhopur"));
            list.add(new State("Rajasthan", "Sikar"));
            list.add(new State("Rajasthan", "Sirohi"));
            list.add(new State("Rajasthan", "Tonk"));
            list.add(new State("Rajasthan", "Udaipur"));
            list.add(new State("Sikkim", "East District"));
            list.add(new State("Sikkim", "North  District"));
            list.add(new State("Sikkim", "South District"));
            list.add(new State("Sikkim", "West District"));
            list.add(new State("Tamil Nadu", "Ariyalur"));
            list.add(new State("Tamil Nadu", "Chennai"));
            list.add(new State("Tamil Nadu", "Coimbatore"));
            list.add(new State("Tamil Nadu", "Cuddalore"));
            list.add(new State("Tamil Nadu", "Dharmapuri"));
            list.add(new State("Tamil Nadu", "Dindigul"));
            list.add(new State("Tamil Nadu", "Erode"));
            list.add(new State("Tamil Nadu", "Kancheepuram"));
            list.add(new State("Tamil Nadu", "Kanniyakumari"));
            list.add(new State("Tamil Nadu", "Karur"));
            list.add(new State("Tamil Nadu", "Krishnagiri"));
            list.add(new State("Tamil Nadu", "Madurai"));
            list.add(new State("Tamil Nadu", "Nagapattinam"));
            list.add(new State("Tamil Nadu", "Namakkal"));
            list.add(new State("Tamil Nadu", "Perambalur"));
            list.add(new State("Tamil Nadu", "Pudukkottai"));
            list.add(new State("Tamil Nadu", "Ramanathapuram"));
            list.add(new State("Tamil Nadu", "Salem"));
            list.add(new State("Tamil Nadu", "Sivaganga"));
            list.add(new State("Tamil Nadu", "Thanjavur"));
            list.add(new State("Tamil Nadu", "The Nilgiris"));
            list.add(new State("Tamil Nadu", "Theni"));
            list.add(new State("Tamil Nadu", "Thiruvallur"));
            list.add(new State("Tamil Nadu", "Thiruvarur"));
            list.add(new State("Tamil Nadu", "Thoothukkudi"));
            list.add(new State("Tamil Nadu", "Tiruchirappalli"));
            list.add(new State("Tamil Nadu", "Tirunelveli"));
            list.add(new State("Tamil Nadu", "Tiruppur"));
            list.add(new State("Tamil Nadu", "Tiruvannamalai"));
            list.add(new State("Tamil Nadu", "Vellore"));
            list.add(new State("Tamil Nadu", "Viluppuram"));
            list.add(new State("Tamil Nadu", "Virudhunagar"));
            list.add(new State("Telangana", "Adilabad"));
            list.add(new State("Telangana", "Hyderabad"));
            list.add(new State("Telangana", "Karimnagar"));
            list.add(new State("Telangana", "Khammam"));
            list.add(new State("Telangana", "Mahbubnagar"));
            list.add(new State("Telangana", "Medak"));
            list.add(new State("Telangana", "Nalgonda"));
            list.add(new State("Telangana", "Nizamabad"));
            list.add(new State("Telangana", "Rangareddy"));
            list.add(new State("Telangana", "Warangal"));
            list.add(new State("Tripura", "Dhalai"));
            list.add(new State("Tripura", "North Tripura"));
            list.add(new State("Tripura", "South Tripura"));
            list.add(new State("Tripura", "West Tripura"));
            list.add(new State("Uttar Pradesh", "Agra"));
            list.add(new State("Uttar Pradesh", "Aligarh"));
            list.add(new State("Uttar Pradesh", "Allahabad"));
            list.add(new State("Uttar Pradesh", "Ambedkar Nagar"));
            list.add(new State("Uttar Pradesh", "Auraiya"));
            list.add(new State("Uttar Pradesh", "Azamgarh"));
            list.add(new State("Uttar Pradesh", "Baghpat"));
            list.add(new State("Uttar Pradesh", "Bahraich"));
            list.add(new State("Uttar Pradesh", "Ballia"));
            list.add(new State("Uttar Pradesh", "Balrampur"));
            list.add(new State("Uttar Pradesh", "Banda"));
            list.add(new State("Uttar Pradesh", "Bara Banki"));
            list.add(new State("Uttar Pradesh", "Bareilly"));
            list.add(new State("Uttar Pradesh", "Basti"));
            list.add(new State("Uttar Pradesh", "Bijnor"));
            list.add(new State("Uttar Pradesh", "Budaun"));
            list.add(new State("Uttar Pradesh", "Bulandshahr"));
            list.add(new State("Uttar Pradesh", "Chandauli"));
            list.add(new State("Uttar Pradesh", "Chitrakoot"));
            list.add(new State("Uttar Pradesh", "Deoria"));
            list.add(new State("Uttar Pradesh", "Etah"));
            list.add(new State("Uttar Pradesh", "Etawah"));
            list.add(new State("Uttar Pradesh", "Faizabad"));
            list.add(new State("Uttar Pradesh", "Farrukhabad"));
            list.add(new State("Uttar Pradesh", "Fatehpur"));
            list.add(new State("Uttar Pradesh", "Firozabad"));
            list.add(new State("Uttar Pradesh", "Gautam Buddha Nagar"));
            list.add(new State("Uttar Pradesh", "Ghaziabad"));
            list.add(new State("Uttar Pradesh", "Ghazipur"));
            list.add(new State("Uttar Pradesh", "Gonda"));
            list.add(new State("Uttar Pradesh", "Gorakhpur"));
            list.add(new State("Uttar Pradesh", "Hamirpur"));
            list.add(new State("Uttar Pradesh", "Hardoi"));
            list.add(new State("Uttar Pradesh", "Jalaun"));
            list.add(new State("Uttar Pradesh", "Jaunpur"));
            list.add(new State("Uttar Pradesh", "Jhansi"));
            list.add(new State("Uttar Pradesh", "Jyotiba Phule Nagar"));
            list.add(new State("Uttar Pradesh", "Kannauj"));
            list.add(new State("Uttar Pradesh", "Kanpur Dehat"));
            list.add(new State("Uttar Pradesh", "Kanpur Nagar"));
            list.add(new State("Uttar Pradesh", "Kanshiram Nagar"));
            list.add(new State("Uttar Pradesh", "Kaushambi"));
            list.add(new State("Uttar Pradesh", "Kheri"));
            list.add(new State("Uttar Pradesh", "Kushinagar"));
            list.add(new State("Uttar Pradesh", "Lalitpur"));
            list.add(new State("Uttar Pradesh", "Lucknow"));
            list.add(new State("Uttar Pradesh", "Mahamaya Nagar"));
            list.add(new State("Uttar Pradesh", "Mahoba"));
            list.add(new State("Uttar Pradesh", "Mahrajganj"));
            list.add(new State("Uttar Pradesh", "Mainpuri"));
            list.add(new State("Uttar Pradesh", "Mathura"));
            list.add(new State("Uttar Pradesh", "Mau"));
            list.add(new State("Uttar Pradesh", "Meerut"));
            list.add(new State("Uttar Pradesh", "Mirzapur"));
            list.add(new State("Uttar Pradesh", "Moradabad"));
            list.add(new State("Uttar Pradesh", "Muzaffarnagar"));
            list.add(new State("Uttar Pradesh", "Pilibhit"));
            list.add(new State("Uttar Pradesh", "Pratapgarh"));
            list.add(new State("Uttar Pradesh", "Rae Bareli"));
            list.add(new State("Uttar Pradesh", "Rampur"));
            list.add(new State("Uttar Pradesh", "Saharanpur"));
            list.add(new State("Uttar Pradesh", "Sant Kabir Nagar"));
            list.add(new State("Uttar Pradesh", "Sant Ravidas Nagar (Bhadohi)"));
            list.add(new State("Uttar Pradesh", "Shahjahanpur"));
            list.add(new State("Uttar Pradesh", "Shrawasti"));
            list.add(new State("Uttar Pradesh", "Siddharth Nagar"));
            list.add(new State("Uttar Pradesh", "Shravasti"));
            list.add(new State("Uttar Pradesh", "Sitapur"));
            list.add(new State("Uttar Pradesh", "Sonbhadra"));
            list.add(new State("Uttar Pradesh", "Sultanpur"));
            list.add(new State("Uttar Pradesh", "Unnao"));
            list.add(new State("Uttar Pradesh", "Varanasi"));
            list.add(new State("Uttar Pradesh", "Barabanki"));
            list.add(new State("Uttar Pradesh", "Ayodhya"));
            list.add(new State("Uttar Pradesh", "Hapur"));
            list.add(new State("Uttar Pradesh", "Hathras"));
            list.add(new State("Uttar Pradesh", "Maharajganj"));
            list.add(new State("Uttar Pradesh", "Raebareli"));
            list.add(new State("Uttar Pradesh", "Kasganj"));
            list.add(new State("Uttar Pradesh", "Sambhal"));
            list.add(new State("Uttar Pradesh", "Shamli"));
            list.add(new State("Uttarakhand", "Almora"));
            list.add(new State("Uttarakhand", "Bageshwar"));
            list.add(new State("Uttarakhand", "Chamoli"));
            list.add(new State("Uttarakhand", "Champawat"));
            list.add(new State("Uttarakhand", "Dehradun"));
            list.add(new State("Uttarakhand", "Garhwal"));
            list.add(new State("Uttarakhand", "Hardwar"));
            list.add(new State("Uttarakhand", "Nainital"));
            list.add(new State("Uttarakhand", "Pithoragarh"));
            list.add(new State("Uttarakhand", "Rudraprayag"));
            list.add(new State("Uttarakhand", "Tehri Garhwal"));
            list.add(new State("Uttarakhand", "Udham Singh Nagar"));
            list.add(new State("Uttarakhand", "Uttarkashi"));
            list.add(new State("West Bengal", "Bankura"));
            list.add(new State("West Bengal", "Barddhaman"));
            list.add(new State("West Bengal", "Birbhum"));
            list.add(new State("West Bengal", "Dakshin Dinajpur"));
            list.add(new State("West Bengal", "Darjiling"));
            list.add(new State("West Bengal", "Haora"));
            list.add(new State("West Bengal", "Hugli"));
            list.add(new State("West Bengal", "Jalpaiguri"));
            list.add(new State("West Bengal", "Koch Bihar"));
            list.add(new State("West Bengal", "Kolkata"));
            list.add(new State("West Bengal", "Maldah"));
            list.add(new State("West Bengal", "Murshidabad"));
            list.add(new State("West Bengal", "Nadia"));
            list.add(new State("West Bengal", "North Twenty Four Parganas"));
            list.add(new State("West Bengal", "Paschim Medinipur"));
            list.add(new State("West Bengal", "Purba Medinipur"));
            list.add(new State("West Bengal", "Puruliya"));
            list.add(new State("West Bengal", "South Twenty Four Parganas"));
            list.add(new State("West Bengal", "Uttar Dinajpur"));

            return list;
        }

    }


    public static class Booking {
        public static final String BOOKING_MODE = "booking_mode";
        public static final String TRAVEL_TYPE = "travel_type";

    }

    public class Vendor {
        public static final String DISTRICT = "district";
        public static final String CONTACT_NAME = "contact_name";
        public static final String DISPLAY_NAME = "display_name";
        public static final String RATE = "rate";
    }

    public class RequestedProject {
        public static final String ID = "id";
        public static final String PROJECT_ID = "project_id";
        public static final String PROJECT_NAME = "project_name";
        public static final String PROJECT_TYPE_ID = "project_type_id";
        public static final String CREATED_BY = "created_by";
        public static final String CREATED_BY_ID = "created_by_id";
    }

    public class FixAsset {
        public static final String ORG_UNIT_ASSET = "org_unit_asset";
        public static final String ORG_UNIT_ASSET_ID = "org_unit_asset_id";
        public static final String REMARK = "remark";
    }
}
